### ISSUE TITLE
Getting error - no process

### ISSUE THREAD

**Issue by anildigital** [cabol/kvx#3]
I have installed kvx as told in README.md but getting following error.

```iex(2)> MyTestMod.new(:mybucket)
** (exit) exited in: :gen_server.call(:shards_sup, {:start_child, [:mybucket, []]}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
             /Users/anil/Projects/standups/deps/shards/src/shards_local.erl:850: :shards_local.new/2
```

I have installed it in my Phoenix app and added below code in config.exs

```config :kvx,
  adapter: KVX.Bucket.Shards,
  ttl: 1,
  shards_mod: :shards
```

**Comment by cabol** [comment]
@anildigital I really sorry the lateness , I hadn't seen this issue. I suppose you found the cause of this error isn't? Otherwise, could you give me more details, e.g.: the application section of your mix file. Remember you haver to add `shards` to the list of your apps. Thanks, I stay tuned!
